services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Log\LoggerInterface:
    class: Psr\Log\NullLogger

  Bic\Foundation\Lifecycle\MainLoop:
    tags:
      - kernel.runnable: ['run']
      - kernel.listener: []
